/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e6e1e0",
        "on-surface": "#1c1b1b",
        "tertiary-fixed": "#e4e1e7",
        "on-tertiary-fixed": "#1b1b1f",
        "outline": "#7d766e",
        "primary-fixed": "#eae1d8",
        "on-secondary": "#ffffff",
        "secondary-container": "#eaddd2",
        "on-error": "#ffffff",
        "surface": "#FAF6F0",
        "surface-container": "#f1edeb",
        "on-tertiary-fixed-variant": "#47464b",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#ece7e6",
        "on-secondary-fixed-variant": "#4d453d",
        "outline-variant": "#E8DFD3",
        "surface-container-low": "#f7f3f1",
        "on-secondary-fixed": "#211b14",
        "secondary-fixed-dim": "#d1c4b9",
        "surface-dim": "#ddd9d8",
        "surface-tint": "#635d57",
        "surface-bright": "#fdf8f7",
        "inverse-surface": "#31302f",
        "tertiary-container": "#1b1b1f",
        "inverse-on-surface": "#f4f0ee",
        "on-primary-fixed-variant": "#4b4640",
        "on-surface-variant": "#4c463f",
        "background": "#FAF6F0",
        "error": "#ba1a1a",
        "on-primary-fixed": "#1f1b16",
        "on-primary": "#ffffff",
        "on-background": "#1c1b1b",
        "error-container": "#ffdad6",
        "on-secondary-container": "#6a6158",
        "primary-container": "#1f1b16",
        "primary": "#000000",
        "tertiary": "#000000",
        "on-primary-container": "#8a837c",
        "primary-fixed-dim": "#cec5bd",
        "on-error-container": "#93000a",
        "inverse-primary": "#cec5bd",
        "tertiary-fixed-dim": "#c8c5cb",
        "secondary-fixed": "#ede0d5",
        "on-tertiary": "#ffffff",
        "secondary": "#665d54",
        "surface-container-highest": "#e6e1e0",
        "on-tertiary-container": "#848388",
        // Spice Tone palette
        "terracotta": "#C1521A",
        "ochre": "#D9A066",
        "sage": "#4C6E4A",
        "plum": "#B5432B",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "12px",
        "xl": "16px",
        "full": "9999px"
      },
      spacing: {
        "container-padding": "32px",
        "section-gap": "48px",
        "element-gap": "24px",
        "grid-gutter": "16px",
        "touch-target": "44px"
      },
      fontFamily: {
        "data-tabular": ["IBM Plex Mono", "monospace"],
        "body-lg": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "display-sm": ["Fraunces", "serif"],
        "headline-md": ["Fraunces", "serif"],
        "display-lg": ["Fraunces", "serif"],
        "label-caps": ["Public Sans", "sans-serif"],
        "display-lg-mobile": ["Fraunces", "serif"]
      },
      fontSize: {
        "data-tabular": ["14px", {"lineHeight": "1.4", "fontWeight": "450"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "display-sm": ["32px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.08em", "fontWeight": "600"}],
        "display-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}]
      },
      keyframes: {
        'pulse-sage': {
          '0%': { transform: 'scale(1)', opacity: '1', borderColor: 'rgba(76, 110, 74, 0.2)' },
          '50%': { transform: 'scale(1.05)', opacity: '0.8', borderColor: 'rgba(76, 110, 74, 0.6)' },
          '100%': { transform: 'scale(1)', opacity: '1', borderColor: 'rgba(76, 110, 74, 0.2)' },
        },
        'fade-in-up': {
          'from': { opacity: '0', transform: 'translateY(20px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'pulse-sage': 'pulse-sage 3s ease-in-out infinite',
        'fade-in-up': 'fade-in-up 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
    },
  },
  plugins: [],
}
